version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  trabalho-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=produtoDB
    ports:
      - "5331:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
