application:
  protocol: http
  url: http://localhost:8033
  name: trabalhoN2
  environment: dev

server:
  port: 8033
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5331/produtoDB
    username: admin
    password: admin
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    enabled: true
    path: /api-docs

